language: node_js

branches:
  only:
    - master
after_success:
  - openssl aes-256-cbc -K $encrypted_ac7c2528d4b9_key -iv $encrypted_ac7c2528d4b9_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - git config --global user.name "ng-flickrdupfinder travis auto deploy"
  - git config --global user.email "linzberger+travis@gmail.com"
  - gulp deploy-travis
